### ISSUE TITLE
Wrong entity reach check

### ISSUE THREAD

**Issue by SplotyCode** [HawkAnticheat/Hawk#12]
For creative the default value is 4.9 i am pretty sure you mixed it up with the block reach what is 4.8 in creative the entity range is 6. I can provide a PR if you agree.

**Comment by Islandscout** [comment]
6 sounds like a lot. Are you sure? The numbers that I entered were based on tests that I conducted. I can test again if necessary. Note that reach in creative slightly changed between versions 1.7 and 1.8

**Comment by SplotyCode** [comment]
I meen 1.8. Kind of wierd but in [this](https://github.com/vmarchaud/Alkazia/blob/master/1.8/Client/src/minecraft/net/minecraft/client/renderer/EntityRenderer.java) in getMouseOver you can see that it is a 6 block range.

**Comment by Islandscout** [comment]
I see that it sets it to 6, but during testing I can't seem to reach higher than 5 blocks.

However, I found out that at different angles, my maximum reach changes drastically. I noticed that at certain angles or at certain positions of the victim, my reach can't go above 4.2, but at other angles or positions, it can go up to 5. It does not appear that the game is directly comparing distance with nearby entities. My hypothesis is that the game is traversing through blocks first.

I'll increase it to 5, but not 6 because I have yet to see a reach value greater than 5.0.
