### ISSUE TITLE
ViaVersion ready?

### ISSUE THREAD

**Issue by german-code** [HawkAnticheat/Hawk#18]
Hey,

i have a question. Can you make an Update to Hawk for ViaVersion (1.7 or 1.8 with ViaVersion)?
We use ViaVersion on a 1.8 Server and players that are joining with 1.9-1.14 get stucked for Fly, NoSwing, FastPlace and so on.

best wishes.

**Comment by Islandscout** [comment]
Hi,

As stated in the overview page on SpigotMC, Hawk is not compatible with clients that are not running 1.7.X or 1.8.X. This is because other clients follow different network protocols and have different code such as for block/entity bounding boxes. Supporting those clients will require rewriting the framework of the anticheat; this is something that I don't have time nor motivation for. Sorry for the inconvenience.
