### ISSUE TITLE
Fast-fall And Sometimes Small-hop False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#33]
if you just jump on slime you will false fast-fall and sometimes small-hop heres a video of it mc version is 1.8.8 https://streamable.com/871vt

**Comment by Islandscout** [comment]
Yeah the client is silly sometimes and it likes to hold off on position updates until the difference in position (I believe) is greater than 0.03 or if 20 ticks have passed since its last position update.

I'm working hard on a position prediction system which should fix this issue in a future update.

**Comment by Islandscout** [comment]
These checks have been replaced by fly and it has been fixed.
