### ISSUE TITLE
GodMode caused by flaggs.

### ISSUE THREAD

**Issue by FelixH2012** [HawkAnticheat/Hawk#62]
https://www.youtube.com/watch?v=Tc_80gAH7so

code: https://pastebin.com/i5QyiExb

**Comment by Islandscout** [comment]
The server is probably making the player invincible after teleport. This is a common occurrence when using plugins such as Essentials.

The code appears to send an invalid move to the server, causing Hawk to set the player back. The set-back is recognized by the server as a teleport (PlayerTeleportEvent). There may be a plugin that grants brief invulnerability to the player after the teleport.

However, in the distant future, I may make the set-backs no longer call Player#teleport() (hence triggering PlayerTeleportEvent). This will fix incompatibility with other plugins.

**Comment by Islandscout** [comment]
I think I fixed my part with the latest commit. To completely fix this, I encourage disabling whatever is producing this player invulnerability (probably Essentials). The reason is because I can think of another way to do this: disable collision and fall through the floor. NMS will rubberband you back up before Hawk catches you, potentially triggering a PlayerTeleportEvent.

**Comment by FelixH2012** [comment]
Fixxed, nice work!
